using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace WaqfSystem.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AutoGeneratedMissingTables : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.RenameIndex(
                name: "IX_Users_RoleId",
                table: "Users",
                newName: "IX_Users_Role");

            migrationBuilder.RenameIndex(
                name: "IX_Users_GovernorateId",
                table: "Users",
                newName: "IX_Users_Gov");

            migrationBuilder.AddColumn<int>(
                name: "DistrictId",
                table: "Users",
                type: "int",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "FailedLoginCount",
                table: "Users",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<bool>(
                name: "IsLocked",
                table: "Users",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<string>(
                name: "JobTitle",
                table: "Users",
                type: "nvarchar(100)",
                maxLength: 100,
                nullable: true,
                collation: "Arabic_CI_AS");

            migrationBuilder.AddColumn<string>(
                name: "LastLoginIp",
                table: "Users",
                type: "nvarchar(50)",
                maxLength: 50,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "LockReason",
                table: "Users",
                type: "nvarchar(500)",
                maxLength: 500,
                nullable: true,
                collation: "Arabic_CI_AS");

            migrationBuilder.AddColumn<DateTime>(
                name: "LockedAt",
                table: "Users",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "LockedById",
                table: "Users",
                type: "int",
                nullable: true);

            migrationBuilder.AddColumn<bool>(
                name: "MustChangePassword",
                table: "Users",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<string>(
                name: "Notes",
                table: "Users",
                type: "nvarchar(1000)",
                maxLength: 1000,
                nullable: true,
                collation: "Arabic_CI_AS");

            migrationBuilder.AddColumn<DateTime>(
                name: "PasswordChangedAt",
                table: "Users",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "Phone",
                table: "Users",
                type: "nvarchar(20)",
                maxLength: 20,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "Phone2",
                table: "Users",
                type: "nvarchar(20)",
                maxLength: 20,
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "SubDistrictId",
                table: "Users",
                type: "int",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "CreatedById",
                table: "SubDistricts",
                type: "int",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "SortOrder",
                table: "SubDistricts",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<int>(
                name: "CreatedById",
                table: "Streets",
                type: "int",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "GisLineId",
                table: "Streets",
                type: "nvarchar(100)",
                maxLength: 100,
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "SortOrder",
                table: "Streets",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<string>(
                name: "StreetType",
                table: "Streets",
                type: "nvarchar(30)",
                maxLength: 30,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "Color",
                table: "Roles",
                type: "nvarchar(20)",
                maxLength: 20,
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "CreatedById",
                table: "Roles",
                type: "int",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "DisplayNameAr",
                table: "Roles",
                type: "nvarchar(100)",
                maxLength: 100,
                nullable: true,
                collation: "Arabic_CI_AS");

            migrationBuilder.AddColumn<string>(
                name: "DisplayNameEn",
                table: "Roles",
                type: "nvarchar(100)",
                maxLength: 100,
                nullable: true);

            migrationBuilder.AddColumn<byte>(
                name: "GeographicScopeLevel",
                table: "Roles",
                type: "tinyint",
                nullable: false,
                defaultValue: (byte)0);

            migrationBuilder.AddColumn<bool>(
                name: "HasGlobalScope",
                table: "Roles",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<string>(
                name: "Icon",
                table: "Roles",
                type: "nvarchar(50)",
                maxLength: 50,
                nullable: true);

            migrationBuilder.AddColumn<bool>(
                name: "IsSystemRole",
                table: "Roles",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<string>(
                name: "Name",
                table: "Roles",
                type: "nvarchar(100)",
                maxLength: 100,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<int>(
                name: "CreatedById",
                table: "Neighborhoods",
                type: "int",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "PostalCode",
                table: "Neighborhoods",
                type: "nvarchar(20)",
                maxLength: 20,
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "SortOrder",
                table: "Neighborhoods",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<string>(
                name: "Type",
                table: "Neighborhoods",
                type: "nvarchar(20)",
                maxLength: 20,
                nullable: false,
                defaultValue: "City");

            migrationBuilder.AddColumn<int>(
                name: "CreatedById",
                table: "Governorates",
                type: "int",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "PostalCode",
                table: "Governorates",
                type: "nvarchar(20)",
                maxLength: 20,
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "SortOrder",
                table: "Governorates",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<int>(
                name: "CreatedById",
                table: "Districts",
                type: "int",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "SortOrder",
                table: "Districts",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.CreateTable(
                name: "Permissions",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    PermissionKey = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    Module = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    Action = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    DisplayNameAr = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: false, collation: "Arabic_CI_AS"),
                    DisplayNameEn = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: false),
                    Description = table.Column<string>(type: "nvarchar(500)", maxLength: 500, nullable: true, collation: "Arabic_CI_AS"),
                    IsActive = table.Column<bool>(type: "bit", nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "datetime2", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Permissions", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "UserGeographicScopes",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    UserId = table.Column<int>(type: "int", nullable: false),
                    ScopeLevel = table.Column<byte>(type: "tinyint", nullable: false),
                    GovernorateId = table.Column<int>(type: "int", nullable: true),
                    DistrictId = table.Column<int>(type: "int", nullable: true),
                    SubDistrictId = table.Column<int>(type: "int", nullable: true),
                    IsPrimary = table.Column<bool>(type: "bit", nullable: false),
                    IsActive = table.Column<bool>(type: "bit", nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "datetime2", nullable: false),
                    CreatedById = table.Column<int>(type: "int", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_UserGeographicScopes", x => x.Id);
                    table.ForeignKey(
                        name: "FK_UserGeographicScopes_Districts_DistrictId",
                        column: x => x.DistrictId,
                        principalTable: "Districts",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_UserGeographicScopes_Governorates_GovernorateId",
                        column: x => x.GovernorateId,
                        principalTable: "Governorates",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_UserGeographicScopes_SubDistricts_SubDistrictId",
                        column: x => x.SubDistrictId,
                        principalTable: "SubDistricts",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_UserGeographicScopes_Users_CreatedById",
                        column: x => x.CreatedById,
                        principalTable: "Users",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_UserGeographicScopes_Users_UserId",
                        column: x => x.UserId,
                        principalTable: "Users",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "RolePermissions",
                columns: table => new
                {
                    RoleId = table.Column<int>(type: "int", nullable: false),
                    PermissionId = table.Column<int>(type: "int", nullable: false),
                    GrantedAt = table.Column<DateTime>(type: "datetime2", nullable: false),
                    GrantedById = table.Column<int>(type: "int", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_RolePermissions", x => new { x.RoleId, x.PermissionId });
                    table.ForeignKey(
                        name: "FK_RolePermissions_Permissions_PermissionId",
                        column: x => x.PermissionId,
                        principalTable: "Permissions",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_RolePermissions_Roles_RoleId",
                        column: x => x.RoleId,
                        principalTable: "Roles",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_RolePermissions_Users_GrantedById",
                        column: x => x.GrantedById,
                        principalTable: "Users",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.UpdateData(
                table: "Countries",
                keyColumn: "Id",
                keyValue: 1,
                column: "CreatedAt",
                value: new DateTime(2026, 3, 15, 12, 18, 27, 489, DateTimeKind.Utc).AddTicks(1486));

            migrationBuilder.UpdateData(
                table: "Governorates",
                keyColumn: "Id",
                keyValue: 1,
                columns: new[] { "CreatedAt", "CreatedById", "PostalCode", "SortOrder" },
                values: new object[] { new DateTime(2026, 3, 15, 12, 18, 27, 489, DateTimeKind.Utc).AddTicks(1635), null, null, 0 });

            migrationBuilder.UpdateData(
                table: "Governorates",
                keyColumn: "Id",
                keyValue: 2,
                columns: new[] { "CreatedAt", "CreatedById", "PostalCode", "SortOrder" },
                values: new object[] { new DateTime(2026, 3, 15, 12, 18, 27, 489, DateTimeKind.Utc).AddTicks(1639), null, null, 0 });

            migrationBuilder.UpdateData(
                table: "Governorates",
                keyColumn: "Id",
                keyValue: 3,
                columns: new[] { "CreatedAt", "CreatedById", "PostalCode", "SortOrder" },
                values: new object[] { new DateTime(2026, 3, 15, 12, 18, 27, 489, DateTimeKind.Utc).AddTicks(1640), null, null, 0 });

            migrationBuilder.UpdateData(
                table: "Governorates",
                keyColumn: "Id",
                keyValue: 4,
                columns: new[] { "CreatedAt", "CreatedById", "PostalCode", "SortOrder" },
                values: new object[] { new DateTime(2026, 3, 15, 12, 18, 27, 489, DateTimeKind.Utc).AddTicks(1641), null, null, 0 });

            migrationBuilder.UpdateData(
                table: "Governorates",
                keyColumn: "Id",
                keyValue: 5,
                columns: new[] { "CreatedAt", "CreatedById", "PostalCode", "SortOrder" },
                values: new object[] { new DateTime(2026, 3, 15, 12, 18, 27, 489, DateTimeKind.Utc).AddTicks(1642), null, null, 0 });

            migrationBuilder.UpdateData(
                table: "Governorates",
                keyColumn: "Id",
                keyValue: 6,
                columns: new[] { "CreatedAt", "CreatedById", "PostalCode", "SortOrder" },
                values: new object[] { new DateTime(2026, 3, 15, 12, 18, 27, 489, DateTimeKind.Utc).AddTicks(1643), null, null, 0 });

            migrationBuilder.UpdateData(
                table: "Governorates",
                keyColumn: "Id",
                keyValue: 7,
                columns: new[] { "CreatedAt", "CreatedById", "PostalCode", "SortOrder" },
                values: new object[] { new DateTime(2026, 3, 15, 12, 18, 27, 489, DateTimeKind.Utc).AddTicks(1644), null, null, 0 });

            migrationBuilder.UpdateData(
                table: "Governorates",
                keyColumn: "Id",
                keyValue: 8,
                columns: new[] { "CreatedAt", "CreatedById", "PostalCode", "SortOrder" },
                values: new object[] { new DateTime(2026, 3, 15, 12, 18, 27, 489, DateTimeKind.Utc).AddTicks(1645), null, null, 0 });

            migrationBuilder.UpdateData(
                table: "Governorates",
                keyColumn: "Id",
                keyValue: 9,
                columns: new[] { "CreatedAt", "CreatedById", "PostalCode", "SortOrder" },
                values: new object[] { new DateTime(2026, 3, 15, 12, 18, 27, 489, DateTimeKind.Utc).AddTicks(1646), null, null, 0 });

            migrationBuilder.UpdateData(
                table: "Governorates",
                keyColumn: "Id",
                keyValue: 10,
                columns: new[] { "CreatedAt", "CreatedById", "PostalCode", "SortOrder" },
                values: new object[] { new DateTime(2026, 3, 15, 12, 18, 27, 489, DateTimeKind.Utc).AddTicks(1647), null, null, 0 });

            migrationBuilder.UpdateData(
                table: "Governorates",
                keyColumn: "Id",
                keyValue: 11,
                columns: new[] { "CreatedAt", "CreatedById", "PostalCode", "SortOrder" },
                values: new object[] { new DateTime(2026, 3, 15, 12, 18, 27, 489, DateTimeKind.Utc).AddTicks(1648), null, null, 0 });

            migrationBuilder.UpdateData(
                table: "Governorates",
                keyColumn: "Id",
                keyValue: 12,
                columns: new[] { "CreatedAt", "CreatedById", "PostalCode", "SortOrder" },
                values: new object[] { new DateTime(2026, 3, 15, 12, 18, 27, 489, DateTimeKind.Utc).AddTicks(1648), null, null, 0 });

            migrationBuilder.UpdateData(
                table: "Governorates",
                keyColumn: "Id",
                keyValue: 13,
                columns: new[] { "CreatedAt", "CreatedById", "PostalCode", "SortOrder" },
                values: new object[] { new DateTime(2026, 3, 15, 12, 18, 27, 489, DateTimeKind.Utc).AddTicks(1649), null, null, 0 });

            migrationBuilder.UpdateData(
                table: "Governorates",
                keyColumn: "Id",
                keyValue: 14,
                columns: new[] { "CreatedAt", "CreatedById", "PostalCode", "SortOrder" },
                values: new object[] { new DateTime(2026, 3, 15, 12, 18, 27, 489, DateTimeKind.Utc).AddTicks(1650), null, null, 0 });

            migrationBuilder.UpdateData(
                table: "Governorates",
                keyColumn: "Id",
                keyValue: 15,
                columns: new[] { "CreatedAt", "CreatedById", "PostalCode", "SortOrder" },
                values: new object[] { new DateTime(2026, 3, 15, 12, 18, 27, 489, DateTimeKind.Utc).AddTicks(1651), null, null, 0 });

            migrationBuilder.UpdateData(
                table: "Governorates",
                keyColumn: "Id",
                keyValue: 16,
                columns: new[] { "CreatedAt", "CreatedById", "PostalCode", "SortOrder" },
                values: new object[] { new DateTime(2026, 3, 15, 12, 18, 27, 489, DateTimeKind.Utc).AddTicks(1652), null, null, 0 });

            migrationBuilder.UpdateData(
                table: "Governorates",
                keyColumn: "Id",
                keyValue: 17,
                columns: new[] { "CreatedAt", "CreatedById", "PostalCode", "SortOrder" },
                values: new object[] { new DateTime(2026, 3, 15, 12, 18, 27, 489, DateTimeKind.Utc).AddTicks(1653), null, null, 0 });

            migrationBuilder.UpdateData(
                table: "Governorates",
                keyColumn: "Id",
                keyValue: 18,
                columns: new[] { "CreatedAt", "CreatedById", "PostalCode", "SortOrder" },
                values: new object[] { new DateTime(2026, 3, 15, 12, 18, 27, 489, DateTimeKind.Utc).AddTicks(1660), null, null, 0 });

            migrationBuilder.UpdateData(
                table: "Roles",
                keyColumn: "Id",
                keyValue: 1,
                columns: new[] { "Color", "CreatedAt", "CreatedById", "DisplayNameAr", "DisplayNameEn", "Icon", "IsSystemRole", "Name" },
                values: new object[] { null, new DateTime(2026, 3, 15, 12, 18, 27, 489, DateTimeKind.Utc).AddTicks(1704), null, null, null, null, false, "" });

            migrationBuilder.UpdateData(
                table: "Roles",
                keyColumn: "Id",
                keyValue: 2,
                columns: new[] { "Color", "CreatedAt", "CreatedById", "DisplayNameAr", "DisplayNameEn", "Icon", "IsSystemRole", "Name" },
                values: new object[] { null, new DateTime(2026, 3, 15, 12, 18, 27, 489, DateTimeKind.Utc).AddTicks(1709), null, null, null, null, false, "" });

            migrationBuilder.UpdateData(
                table: "Roles",
                keyColumn: "Id",
                keyValue: 3,
                columns: new[] { "Color", "CreatedAt", "CreatedById", "DisplayNameAr", "DisplayNameEn", "Icon", "IsSystemRole", "Name" },
                values: new object[] { null, new DateTime(2026, 3, 15, 12, 18, 27, 489, DateTimeKind.Utc).AddTicks(1711), null, null, null, null, false, "" });

            migrationBuilder.UpdateData(
                table: "Roles",
                keyColumn: "Id",
                keyValue: 4,
                columns: new[] { "Color", "CreatedAt", "CreatedById", "DisplayNameAr", "DisplayNameEn", "Icon", "IsSystemRole", "Name" },
                values: new object[] { null, new DateTime(2026, 3, 15, 12, 18, 27, 489, DateTimeKind.Utc).AddTicks(1712), null, null, null, null, false, "" });

            migrationBuilder.UpdateData(
                table: "Roles",
                keyColumn: "Id",
                keyValue: 5,
                columns: new[] { "Color", "CreatedAt", "CreatedById", "DisplayNameAr", "DisplayNameEn", "Icon", "IsSystemRole", "Name" },
                values: new object[] { null, new DateTime(2026, 3, 15, 12, 18, 27, 489, DateTimeKind.Utc).AddTicks(1713), null, null, null, null, false, "" });

            migrationBuilder.UpdateData(
                table: "Roles",
                keyColumn: "Id",
                keyValue: 6,
                columns: new[] { "Color", "CreatedAt", "CreatedById", "DisplayNameAr", "DisplayNameEn", "Icon", "IsSystemRole", "Name" },
                values: new object[] { null, new DateTime(2026, 3, 15, 12, 18, 27, 489, DateTimeKind.Utc).AddTicks(1713), null, null, null, null, false, "" });

            migrationBuilder.UpdateData(
                table: "Roles",
                keyColumn: "Id",
                keyValue: 7,
                columns: new[] { "Color", "CreatedAt", "CreatedById", "DisplayNameAr", "DisplayNameEn", "Icon", "IsSystemRole", "Name" },
                values: new object[] { null, new DateTime(2026, 3, 15, 12, 18, 27, 489, DateTimeKind.Utc).AddTicks(1717), null, null, null, null, false, "" });

            migrationBuilder.UpdateData(
                table: "Roles",
                keyColumn: "Id",
                keyValue: 8,
                columns: new[] { "Color", "CreatedAt", "CreatedById", "DisplayNameAr", "DisplayNameEn", "Icon", "IsSystemRole", "Name" },
                values: new object[] { null, new DateTime(2026, 3, 15, 12, 18, 27, 489, DateTimeKind.Utc).AddTicks(1718), null, null, null, null, false, "" });

            migrationBuilder.UpdateData(
                table: "Roles",
                keyColumn: "Id",
                keyValue: 9,
                columns: new[] { "Color", "CreatedAt", "CreatedById", "DisplayNameAr", "DisplayNameEn", "Icon", "IsSystemRole", "Name" },
                values: new object[] { null, new DateTime(2026, 3, 15, 12, 18, 27, 489, DateTimeKind.Utc).AddTicks(1719), null, null, null, null, false, "" });

            migrationBuilder.UpdateData(
                table: "Roles",
                keyColumn: "Id",
                keyValue: 10,
                columns: new[] { "Color", "CreatedAt", "CreatedById", "DisplayNameAr", "DisplayNameEn", "Icon", "IsSystemRole", "Name" },
                values: new object[] { null, new DateTime(2026, 3, 15, 12, 18, 27, 489, DateTimeKind.Utc).AddTicks(1719), null, null, null, null, false, "" });

            migrationBuilder.UpdateData(
                table: "Users",
                keyColumn: "Id",
                keyValue: 1,
                columns: new[] { "DistrictId", "FailedLoginCount", "IsLocked", "JobTitle", "LastLoginIp", "LockReason", "LockedAt", "LockedById", "MustChangePassword", "Notes", "PasswordChangedAt", "Phone", "Phone2", "SubDistrictId" },
                values: new object[] { null, 0, false, null, null, null, null, null, false, null, null, null, null, null });

            migrationBuilder.CreateIndex(
                name: "IX_Users_District",
                table: "Users",
                column: "DistrictId");

            migrationBuilder.CreateIndex(
                name: "IX_Users_LockedById",
                table: "Users",
                column: "LockedById");

            migrationBuilder.CreateIndex(
                name: "IX_Users_SubDistrict",
                table: "Users",
                column: "SubDistrictId");

            migrationBuilder.CreateIndex(
                name: "IX_SubDist_Dist",
                table: "SubDistricts",
                columns: new[] { "DistrictId", "IsActive" });

            migrationBuilder.CreateIndex(
                name: "IX_Street_Neigh",
                table: "Streets",
                columns: new[] { "NeighborhoodId", "IsActive" });

            migrationBuilder.CreateIndex(
                name: "IX_Roles_CreatedById",
                table: "Roles",
                column: "CreatedById");

            migrationBuilder.CreateIndex(
                name: "IX_Neigh_Sub",
                table: "Neighborhoods",
                columns: new[] { "SubDistrictId", "IsActive" });

            migrationBuilder.CreateIndex(
                name: "IX_Gov_Active",
                table: "Governorates",
                columns: new[] { "IsActive", "SortOrder" });

            migrationBuilder.CreateIndex(
                name: "IX_District_Gov",
                table: "Districts",
                columns: new[] { "GovernorateId", "IsActive" });

            migrationBuilder.CreateIndex(
                name: "IX_Permissions_Module_IsActive",
                table: "Permissions",
                columns: new[] { "Module", "IsActive" });

            migrationBuilder.CreateIndex(
                name: "IX_Permissions_PermissionKey",
                table: "Permissions",
                column: "PermissionKey",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_RolePermissions_GrantedById",
                table: "RolePermissions",
                column: "GrantedById");

            migrationBuilder.CreateIndex(
                name: "IX_RolePermissions_PermissionId",
                table: "RolePermissions",
                column: "PermissionId");

            migrationBuilder.CreateIndex(
                name: "IX_RolePerms_Role",
                table: "RolePermissions",
                column: "RoleId");

            migrationBuilder.CreateIndex(
                name: "IX_UserGeographicScopes_CreatedById",
                table: "UserGeographicScopes",
                column: "CreatedById");

            migrationBuilder.CreateIndex(
                name: "IX_UserGeographicScopes_DistrictId",
                table: "UserGeographicScopes",
                column: "DistrictId");

            migrationBuilder.CreateIndex(
                name: "IX_UserGeographicScopes_GovernorateId",
                table: "UserGeographicScopes",
                column: "GovernorateId");

            migrationBuilder.CreateIndex(
                name: "IX_UserGeographicScopes_SubDistrictId",
                table: "UserGeographicScopes",
                column: "SubDistrictId");

            migrationBuilder.CreateIndex(
                name: "IX_UserGeoScope_UserScope",
                table: "UserGeographicScopes",
                columns: new[] { "UserId", "ScopeLevel", "GovernorateId", "DistrictId", "SubDistrictId" });

            migrationBuilder.AddForeignKey(
                name: "FK_Roles_Users_CreatedById",
                table: "Roles",
                column: "CreatedById",
                principalTable: "Users",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_Users_Districts_DistrictId",
                table: "Users",
                column: "DistrictId",
                principalTable: "Districts",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_Users_SubDistricts_SubDistrictId",
                table: "Users",
                column: "SubDistrictId",
                principalTable: "SubDistricts",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_Users_Users_LockedById",
                table: "Users",
                column: "LockedById",
                principalTable: "Users",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Roles_Users_CreatedById",
                table: "Roles");

            migrationBuilder.DropForeignKey(
                name: "FK_Users_Districts_DistrictId",
                table: "Users");

            migrationBuilder.DropForeignKey(
                name: "FK_Users_SubDistricts_SubDistrictId",
                table: "Users");

            migrationBuilder.DropForeignKey(
                name: "FK_Users_Users_LockedById",
                table: "Users");

            migrationBuilder.DropTable(
                name: "RolePermissions");

            migrationBuilder.DropTable(
                name: "UserGeographicScopes");

            migrationBuilder.DropTable(
                name: "Permissions");

            migrationBuilder.DropIndex(
                name: "IX_Users_District",
                table: "Users");

            migrationBuilder.DropIndex(
                name: "IX_Users_LockedById",
                table: "Users");

            migrationBuilder.DropIndex(
                name: "IX_Users_SubDistrict",
                table: "Users");

            migrationBuilder.DropIndex(
                name: "IX_SubDist_Dist",
                table: "SubDistricts");

            migrationBuilder.DropIndex(
                name: "IX_Street_Neigh",
                table: "Streets");

            migrationBuilder.DropIndex(
                name: "IX_Roles_CreatedById",
                table: "Roles");

            migrationBuilder.DropIndex(
                name: "IX_Neigh_Sub",
                table: "Neighborhoods");

            migrationBuilder.DropIndex(
                name: "IX_Gov_Active",
                table: "Governorates");

            migrationBuilder.DropIndex(
                name: "IX_District_Gov",
                table: "Districts");

            migrationBuilder.DropColumn(
                name: "DistrictId",
                table: "Users");

            migrationBuilder.DropColumn(
                name: "FailedLoginCount",
                table: "Users");

            migrationBuilder.DropColumn(
                name: "IsLocked",
                table: "Users");

            migrationBuilder.DropColumn(
                name: "JobTitle",
                table: "Users");

            migrationBuilder.DropColumn(
                name: "LastLoginIp",
                table: "Users");

            migrationBuilder.DropColumn(
                name: "LockReason",
                table: "Users");

            migrationBuilder.DropColumn(
                name: "LockedAt",
                table: "Users");

            migrationBuilder.DropColumn(
                name: "LockedById",
                table: "Users");

            migrationBuilder.DropColumn(
                name: "MustChangePassword",
                table: "Users");

            migrationBuilder.DropColumn(
                name: "Notes",
                table: "Users");

            migrationBuilder.DropColumn(
                name: "PasswordChangedAt",
                table: "Users");

            migrationBuilder.DropColumn(
                name: "Phone",
                table: "Users");

            migrationBuilder.DropColumn(
                name: "Phone2",
                table: "Users");

            migrationBuilder.DropColumn(
                name: "SubDistrictId",
                table: "Users");

            migrationBuilder.DropColumn(
                name: "CreatedById",
                table: "SubDistricts");

            migrationBuilder.DropColumn(
                name: "SortOrder",
                table: "SubDistricts");

            migrationBuilder.DropColumn(
                name: "CreatedById",
                table: "Streets");

            migrationBuilder.DropColumn(
                name: "GisLineId",
                table: "Streets");

            migrationBuilder.DropColumn(
                name: "SortOrder",
                table: "Streets");

            migrationBuilder.DropColumn(
                name: "StreetType",
                table: "Streets");

            migrationBuilder.DropColumn(
                name: "Color",
                table: "Roles");

            migrationBuilder.DropColumn(
                name: "CreatedById",
                table: "Roles");

            migrationBuilder.DropColumn(
                name: "DisplayNameAr",
                table: "Roles");

            migrationBuilder.DropColumn(
                name: "DisplayNameEn",
                table: "Roles");

            migrationBuilder.DropColumn(
                name: "GeographicScopeLevel",
                table: "Roles");

            migrationBuilder.DropColumn(
                name: "HasGlobalScope",
                table: "Roles");

            migrationBuilder.DropColumn(
                name: "Icon",
                table: "Roles");

            migrationBuilder.DropColumn(
                name: "IsSystemRole",
                table: "Roles");

            migrationBuilder.DropColumn(
                name: "Name",
                table: "Roles");

            migrationBuilder.DropColumn(
                name: "CreatedById",
                table: "Neighborhoods");

            migrationBuilder.DropColumn(
                name: "PostalCode",
                table: "Neighborhoods");

            migrationBuilder.DropColumn(
                name: "SortOrder",
                table: "Neighborhoods");

            migrationBuilder.DropColumn(
                name: "Type",
                table: "Neighborhoods");

            migrationBuilder.DropColumn(
                name: "CreatedById",
                table: "Governorates");

            migrationBuilder.DropColumn(
                name: "PostalCode",
                table: "Governorates");

            migrationBuilder.DropColumn(
                name: "SortOrder",
                table: "Governorates");

            migrationBuilder.DropColumn(
                name: "CreatedById",
                table: "Districts");

            migrationBuilder.DropColumn(
                name: "SortOrder",
                table: "Districts");

            migrationBuilder.RenameIndex(
                name: "IX_Users_Role",
                table: "Users",
                newName: "IX_Users_RoleId");

            migrationBuilder.RenameIndex(
                name: "IX_Users_Gov",
                table: "Users",
                newName: "IX_Users_GovernorateId");

            migrationBuilder.UpdateData(
                table: "Countries",
                keyColumn: "Id",
                keyValue: 1,
                column: "CreatedAt",
                value: new DateTime(2026, 3, 14, 20, 5, 38, 544, DateTimeKind.Utc).AddTicks(9366));

            migrationBuilder.UpdateData(
                table: "Governorates",
                keyColumn: "Id",
                keyValue: 1,
                column: "CreatedAt",
                value: new DateTime(2026, 3, 14, 20, 5, 38, 544, DateTimeKind.Utc).AddTicks(9890));

            migrationBuilder.UpdateData(
                table: "Governorates",
                keyColumn: "Id",
                keyValue: 2,
                column: "CreatedAt",
                value: new DateTime(2026, 3, 14, 20, 5, 38, 544, DateTimeKind.Utc).AddTicks(9903));

            migrationBuilder.UpdateData(
                table: "Governorates",
                keyColumn: "Id",
                keyValue: 3,
                column: "CreatedAt",
                value: new DateTime(2026, 3, 14, 20, 5, 38, 544, DateTimeKind.Utc).AddTicks(9905));

            migrationBuilder.UpdateData(
                table: "Governorates",
                keyColumn: "Id",
                keyValue: 4,
                column: "CreatedAt",
                value: new DateTime(2026, 3, 14, 20, 5, 38, 544, DateTimeKind.Utc).AddTicks(9906));

            migrationBuilder.UpdateData(
                table: "Governorates",
                keyColumn: "Id",
                keyValue: 5,
                column: "CreatedAt",
                value: new DateTime(2026, 3, 14, 20, 5, 38, 544, DateTimeKind.Utc).AddTicks(9907));

            migrationBuilder.UpdateData(
                table: "Governorates",
                keyColumn: "Id",
                keyValue: 6,
                column: "CreatedAt",
                value: new DateTime(2026, 3, 14, 20, 5, 38, 544, DateTimeKind.Utc).AddTicks(9910));

            migrationBuilder.UpdateData(
                table: "Governorates",
                keyColumn: "Id",
                keyValue: 7,
                column: "CreatedAt",
                value: new DateTime(2026, 3, 14, 20, 5, 38, 544, DateTimeKind.Utc).AddTicks(9911));

            migrationBuilder.UpdateData(
                table: "Governorates",
                keyColumn: "Id",
                keyValue: 8,
                column: "CreatedAt",
                value: new DateTime(2026, 3, 14, 20, 5, 38, 544, DateTimeKind.Utc).AddTicks(9912));

            migrationBuilder.UpdateData(
                table: "Governorates",
                keyColumn: "Id",
                keyValue: 9,
                column: "CreatedAt",
                value: new DateTime(2026, 3, 14, 20, 5, 38, 544, DateTimeKind.Utc).AddTicks(9913));

            migrationBuilder.UpdateData(
                table: "Governorates",
                keyColumn: "Id",
                keyValue: 10,
                column: "CreatedAt",
                value: new DateTime(2026, 3, 14, 20, 5, 38, 544, DateTimeKind.Utc).AddTicks(9914));

            migrationBuilder.UpdateData(
                table: "Governorates",
                keyColumn: "Id",
                keyValue: 11,
                column: "CreatedAt",
                value: new DateTime(2026, 3, 14, 20, 5, 38, 544, DateTimeKind.Utc).AddTicks(9915));

            migrationBuilder.UpdateData(
                table: "Governorates",
                keyColumn: "Id",
                keyValue: 12,
                column: "CreatedAt",
                value: new DateTime(2026, 3, 14, 20, 5, 38, 544, DateTimeKind.Utc).AddTicks(9916));

            migrationBuilder.UpdateData(
                table: "Governorates",
                keyColumn: "Id",
                keyValue: 13,
                column: "CreatedAt",
                value: new DateTime(2026, 3, 14, 20, 5, 38, 544, DateTimeKind.Utc).AddTicks(9955));

            migrationBuilder.UpdateData(
                table: "Governorates",
                keyColumn: "Id",
                keyValue: 14,
                column: "CreatedAt",
                value: new DateTime(2026, 3, 14, 20, 5, 38, 544, DateTimeKind.Utc).AddTicks(9956));

            migrationBuilder.UpdateData(
                table: "Governorates",
                keyColumn: "Id",
                keyValue: 15,
                column: "CreatedAt",
                value: new DateTime(2026, 3, 14, 20, 5, 38, 544, DateTimeKind.Utc).AddTicks(9957));

            migrationBuilder.UpdateData(
                table: "Governorates",
                keyColumn: "Id",
                keyValue: 16,
                column: "CreatedAt",
                value: new DateTime(2026, 3, 14, 20, 5, 38, 544, DateTimeKind.Utc).AddTicks(9959));

            migrationBuilder.UpdateData(
                table: "Governorates",
                keyColumn: "Id",
                keyValue: 17,
                column: "CreatedAt",
                value: new DateTime(2026, 3, 14, 20, 5, 38, 544, DateTimeKind.Utc).AddTicks(9960));

            migrationBuilder.UpdateData(
                table: "Governorates",
                keyColumn: "Id",
                keyValue: 18,
                column: "CreatedAt",
                value: new DateTime(2026, 3, 14, 20, 5, 38, 544, DateTimeKind.Utc).AddTicks(9961));

            migrationBuilder.UpdateData(
                table: "Roles",
                keyColumn: "Id",
                keyValue: 1,
                column: "CreatedAt",
                value: new DateTime(2026, 3, 14, 20, 5, 38, 545, DateTimeKind.Utc).AddTicks(16));

            migrationBuilder.UpdateData(
                table: "Roles",
                keyColumn: "Id",
                keyValue: 2,
                column: "CreatedAt",
                value: new DateTime(2026, 3, 14, 20, 5, 38, 545, DateTimeKind.Utc).AddTicks(29));

            migrationBuilder.UpdateData(
                table: "Roles",
                keyColumn: "Id",
                keyValue: 3,
                column: "CreatedAt",
                value: new DateTime(2026, 3, 14, 20, 5, 38, 545, DateTimeKind.Utc).AddTicks(30));

            migrationBuilder.UpdateData(
                table: "Roles",
                keyColumn: "Id",
                keyValue: 4,
                column: "CreatedAt",
                value: new DateTime(2026, 3, 14, 20, 5, 38, 545, DateTimeKind.Utc).AddTicks(31));

            migrationBuilder.UpdateData(
                table: "Roles",
                keyColumn: "Id",
                keyValue: 5,
                column: "CreatedAt",
                value: new DateTime(2026, 3, 14, 20, 5, 38, 545, DateTimeKind.Utc).AddTicks(32));

            migrationBuilder.UpdateData(
                table: "Roles",
                keyColumn: "Id",
                keyValue: 6,
                column: "CreatedAt",
                value: new DateTime(2026, 3, 14, 20, 5, 38, 545, DateTimeKind.Utc).AddTicks(33));

            migrationBuilder.UpdateData(
                table: "Roles",
                keyColumn: "Id",
                keyValue: 7,
                column: "CreatedAt",
                value: new DateTime(2026, 3, 14, 20, 5, 38, 545, DateTimeKind.Utc).AddTicks(34));

            migrationBuilder.UpdateData(
                table: "Roles",
                keyColumn: "Id",
                keyValue: 8,
                column: "CreatedAt",
                value: new DateTime(2026, 3, 14, 20, 5, 38, 545, DateTimeKind.Utc).AddTicks(35));

            migrationBuilder.UpdateData(
                table: "Roles",
                keyColumn: "Id",
                keyValue: 9,
                column: "CreatedAt",
                value: new DateTime(2026, 3, 14, 20, 5, 38, 545, DateTimeKind.Utc).AddTicks(36));

            migrationBuilder.UpdateData(
                table: "Roles",
                keyColumn: "Id",
                keyValue: 10,
                column: "CreatedAt",
                value: new DateTime(2026, 3, 14, 20, 5, 38, 545, DateTimeKind.Utc).AddTicks(37));
        }
    }
}
